ci: add `cargo clippy` to ci pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -7,23 +7,24 @@ on:
 
 jobs:
   build_and_test:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Build and test rust solutions
+      - name: Build, lint and test rust solutions
         run: |
           for d in */; do
             if [[ -f "$d/Cargo.toml" ]]; then
               cd "$d"
               printf '\n\nChecking %s\n\n' "$d"
               cargo check || printf '%s\n' "$d" >> failures
+              cargo clippy || printf '%s\n' "$d" >> failures
               cargo test || printf '%s\n' "$d" >> failures
               cd -
             fi
           done
 
           if [[ -f failures ]]; then
-            printf 'One or more tests failed:\n' 1>&2
+            printf 'One or more solutions failed:\n' 1>&2
             cat failure 1>&2
             exit 1
           fi
