ci: pipeline should fail if one or more tests fail (#1)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,15 +16,16 @@ jobs:
             if [[ -f "$d/Cargo.toml" ]]; then
               cd "$d"
               printf '\n\nChecking %s\n\n' "$d"
-              cargo check || printf '%s\n' "$d" >> failures
-              cargo clippy || printf '%s\n' "$d" >> failures
-              cargo test || printf '%s\n' "$d" >> failures
-              cd -
+              cargo check || printf '%s\n' "$d" >> ../failures
+              cargo clippy || printf '%s\n' "$d" >> ../failures
+              cargo test || printf '%s\n' "$d" >> ../failures
+              printf '\n========================================================\n'
+              cd - 1>/dev/null
             fi
           done
 
           if [[ -f failures ]]; then
             printf 'One or more solutions failed:\n' 1>&2
-            cat failure 1>&2
+            cat failures 1>&2
             exit 1
           fi
